services:
  - type: web
    name: fastapi-task-manager
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        sync: false
        value: postgres://<username>:<password>@<host>:<port>/<db_name>